### ISSUE TITLE
After installing Kite, It doesn´t show anything, it doesn´t work

### ISSUE THREAD

**Issue by peleon02** [kiteco/KiteSublime#5]
Hi, Im on the last build of ST3 3174, and I installed, the package manager, a theme and kite (From the windows app, not cloned from github), and it doesn´t work, this is the Kite related, in the console

Windows 10 PRO x64
python 3.7.1 last build x64

```reloading plugin KiteSublime.KiteSublime
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\KiteSublime\KiteSublime.py", line 15, in <module>
    from .lib.commands import *
  File "C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\KiteSublime\lib\commands.py", line 5, in <module>
    from ..lib.handlers import HoverHandler, SignaturesHandler
  File "C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\KiteSublime\lib\handlers.py", line 13, in <module>
    from ..vendor.jinja2 import Template
  File "C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\KiteSublime\vendor\jinja2\__init__.py", line 56, in <module>
    from jinja2.utils import Markup, escape, clear_caches, \
ImportError: cannot import name select_autoescape
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-10-26 22:06:45, next run at 2018-10-26 23:06:45 or after
```

**Comment by dhung09** [comment]
Hi @peleon02, just wanted to confirm that you've tried restarting Sublime and this is the error that's shown on restart?

What other packages do you have installed?

**Comment by peleon02** [comment]
> Hi @peleon02, just wanted to confirm that you've tried restarting Sublime and this is the error that's shown on restart?
> 
> What other packages do you have installed?

Yes, I´ve tried to do that  3 times

**Comment by dhung09** [comment]
A couple of things to help debug this issue further:

1. What are the contents in `C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\`?
2. What is the output of the command in the Sublime console: `import sys; print(sys.path)`?
3. What is the output of the command in the Sublime console: `import jinja2; print(jinja2.__version__)`?

**Comment by peleon02** [comment]
> A couple of things to help debug this issue further:
> 
> 1. What are the contents in `C:\Users\Kevin\AppData\Roaming\Sublime Text 3\Packages\`?
> 2. What is the output of the command in the Sublime console: `import sys; print(sys.path)`?
> 3. What is the output of the command in the Sublime console: `import jinja2; print(jinja2.__version__)`?

As I had unistalled it, I install it back (st3 I mean) and Now is working, thanks for fast answer

Yes I had installed it like 3 times and now it works
